
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'leftPLUSMINUSleftTIMESDIVIDEASSIGN BEGIN COLON COMMA DIVIDE DO DOT ELSE END EQ FUNCTION GE GT ID IF LE LPAREN LT MINUS NEQ NUMBER PLUS PROCEDURE PROGRAM RPAREN SEMI THEN TIMES VAR WHILEprogram : PROGRAM ID SEMI declarations BEGIN stmt_list END DOTdeclarations : VAR var_declarations\n                    | emptyvar_declarations : var_declarations var_declaration\n                        | var_declarationvar_declaration : ID_list COLON ID SEMIID_list : ID\n               | ID_list COMMA IDstmt_list : stmt_list stmt\n                 | stmtstmt : ID ASSIGN expr SEMI\n            | block\n            | WHILE expr DO stmtblock : BEGIN stmt_list ENDexpr : expr PLUS term\n            | expr MINUS term\n            | termterm : term TIMES factor\n            | term DIVIDE factor\n            | factorfactor : NUMBER\n              | ID\n              | LPAREN expr RPARENempty :'
    
_lr_action_items = {'PROGRAM':([0,],[2,]),'$end':([1,36,],[0,-1,]),'ID':([2,6,8,9,10,14,15,16,17,18,19,20,21,22,23,25,31,35,37,38,39,40,41,43,44,45,],[3,12,13,12,-5,13,13,-10,-12,30,-4,32,33,30,13,-9,30,-14,13,30,30,30,30,-6,-11,-13,]),'SEMI':([3,27,28,29,30,32,34,46,47,48,49,50,],[4,-17,-20,-21,-22,43,44,-15,-16,-18,-19,-23,]),'VAR':([4,],[6,]),'BEGIN':([4,5,7,8,9,10,14,15,16,17,19,23,25,35,37,43,44,45,],[-24,8,-3,14,-2,-5,14,14,-10,-12,-4,14,-9,-14,14,-6,-11,-13,]),'WHILE':([8,14,15,16,17,23,25,35,37,44,45,],[18,18,18,-10,-12,18,-9,-14,18,-11,-13,]),'COLON':([11,12,33,],[20,-7,-8,]),'COMMA':([11,12,33,],[21,-7,-8,]),'ASSIGN':([13,],[22,]),'END':([15,16,17,23,25,35,44,45,],[24,-10,-12,35,-9,-14,-11,-13,]),'NUMBER':([18,22,31,38,39,40,41,],[29,29,29,29,29,29,29,]),'LPAREN':([18,22,31,38,39,40,41,],[31,31,31,31,31,31,31,]),'DOT':([24,],[36,]),'DO':([26,27,28,29,30,46,47,48,49,50,],[37,-17,-20,-21,-22,-15,-16,-18,-19,-23,]),'PLUS':([26,27,28,29,30,34,42,46,47,48,49,50,],[38,-17,-20,-21,-22,38,38,-15,-16,-18,-19,-23,]),'MINUS':([26,27,28,29,30,34,42,46,47,48,49,50,],[39,-17,-20,-21,-22,39,39,-15,-16,-18,-19,-23,]),'RPAREN':([27,28,29,30,42,46,47,48,49,50,],[-17,-20,-21,-22,50,-15,-16,-18,-19,-23,]),'TIMES':([27,28,29,30,46,47,48,49,50,],[40,-20,-21,-22,40,40,-18,-19,-23,]),'DIVIDE':([27,28,29,30,46,47,48,49,50,],[41,-20,-21,-22,41,41,-18,-19,-23,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'program':([0,],[1,]),'declarations':([4,],[5,]),'empty':([4,],[7,]),'var_declarations':([6,],[9,]),'var_declaration':([6,9,],[10,19,]),'ID_list':([6,9,],[11,11,]),'stmt_list':([8,14,],[15,23,]),'stmt':([8,14,15,23,37,],[16,16,25,25,45,]),'block':([8,14,15,23,37,],[17,17,17,17,17,]),'expr':([18,22,31,],[26,34,42,]),'term':([18,22,31,38,39,],[27,27,27,46,47,]),'factor':([18,22,31,38,39,40,41,],[28,28,28,28,28,48,49,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> program","S'",1,None,None,None),
  ('program -> PROGRAM ID SEMI declarations BEGIN stmt_list END DOT','program',8,'p_program','main.py',83),
  ('declarations -> VAR var_declarations','declarations',2,'p_declarations','main.py',87),
  ('declarations -> empty','declarations',1,'p_declarations','main.py',88),
  ('var_declarations -> var_declarations var_declaration','var_declarations',2,'p_var_declarations','main.py',92),
  ('var_declarations -> var_declaration','var_declarations',1,'p_var_declarations','main.py',93),
  ('var_declaration -> ID_list COLON ID SEMI','var_declaration',4,'p_var_declaration','main.py',100),
  ('ID_list -> ID','ID_list',1,'p_ID_list','main.py',104),
  ('ID_list -> ID_list COMMA ID','ID_list',3,'p_ID_list','main.py',105),
  ('stmt_list -> stmt_list stmt','stmt_list',2,'p_stmt_list','main.py',112),
  ('stmt_list -> stmt','stmt_list',1,'p_stmt_list','main.py',113),
  ('stmt -> ID ASSIGN expr SEMI','stmt',4,'p_stmt','main.py',120),
  ('stmt -> block','stmt',1,'p_stmt','main.py',121),
  ('stmt -> WHILE expr DO stmt','stmt',4,'p_stmt','main.py',122),
  ('block -> BEGIN stmt_list END','block',3,'p_block','main.py',131),
  ('expr -> expr PLUS term','expr',3,'p_expr','main.py',135),
  ('expr -> expr MINUS term','expr',3,'p_expr','main.py',136),
  ('expr -> term','expr',1,'p_expr','main.py',137),
  ('term -> term TIMES factor','term',3,'p_term','main.py',144),
  ('term -> term DIVIDE factor','term',3,'p_term','main.py',145),
  ('term -> factor','term',1,'p_term','main.py',146),
  ('factor -> NUMBER','factor',1,'p_factor','main.py',153),
  ('factor -> ID','factor',1,'p_factor','main.py',154),
  ('factor -> LPAREN expr RPAREN','factor',3,'p_factor','main.py',155),
  ('empty -> <empty>','empty',0,'p_empty','main.py',164),
]
